// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class ejemploFinal
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string trabajo { get; set; }
        public int? cantidaTrabajo { get; set; }
        public string Hobbie { get; set; }
        public int? cantidaHobies { get; set; }
    }
}