// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class ejemplo
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string Trabajodatos { get; set; }
        public string Hobiedatos { get; set; }
    }
}