// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbAsiento
    {
        public tbAsiento()
        {
            tbTickets = new HashSet<tbTicket>();
        }

        public int asie_Id { get; set; }
        public int asie_Sala { get; set; }
        public string asie_Code { get; set; }
        public bool? asie_Reservado { get; set; }
        public int asie_UserCrea { get; set; }
        public DateTime asie_FechaCrea { get; set; }
        public int? asie_UserMofica { get; set; }
        public DateTime? asie_FechaModifica { get; set; }

        public virtual tbSala asie_SalaNavigation { get; set; }
        public virtual tbUsuario asie_UserCreaNavigation { get; set; }
        public virtual tbUsuario asie_UserMoficaNavigation { get; set; }
        public virtual ICollection<tbTicket> tbTickets { get; set; }
    }
}