// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbCategoria
    {
        public tbCategoria()
        {
            tbPeliculas = new HashSet<tbPelicula>();
        }

        public int cate_Id { get; set; }
        public string cate_Nombre { get; set; }
        public bool? cate_Estado { get; set; }
        public int? cate_UsuarioCreador { get; set; }
        public DateTime? cate_FechaCreacion { get; set; }
        public int? cate_UsuarioModificador { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }

        public virtual tbUsuario cate_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuario cate_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPelicula> tbPeliculas { get; set; }
    }
}