// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbCargo
    {
        public tbCargo()
        {
            tbEmpleados = new HashSet<tbEmpleado>();
        }

        public int carg_Id { get; set; }
        public string carg_Cargo { get; set; }
        public bool? car_Estado { get; set; }
        public int carg_UsuarioCreador { get; set; }
        public DateTime? carg_FechaCreacion { get; set; }
        public int? carg_UsuarioModificado { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }

        public virtual tbUsuario carg_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuario carg_UsuarioModificadoNavigation { get; set; }
        public virtual ICollection<tbEmpleado> tbEmpleados { get; set; }
    }
}