// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbCliente
    {
        public tbCliente()
        {
            tbFacturas = new HashSet<tbFactura>();
        }

        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_RTN { get; set; }
        public bool? clie_Estado { get; set; }
        public int clie_UserCrea { get; set; }
        public DateTime? clie_FechaCrea { get; set; }
        public int? clie_UserModifica { get; set; }
        public DateTime? clie_FechaModifica { get; set; }

        public virtual tbUsuario clie_UserCreaNavigation { get; set; }
        public virtual tbUsuario clie_UserModificaNavigation { get; set; }
        public virtual ICollection<tbFactura> tbFacturas { get; set; }
    }
}