// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbComboDetalle
    {
        public tbComboDetalle()
        {
            tbFacturaDetalles = new HashSet<tbFacturaDetalle>();
        }

        public int cdet_Id { get; set; }
        public int cdet_combId { get; set; }
        public int cdet_insuId { get; set; }
        public bool? cdet_Estado { get; set; }
        public int cdet_UserCrea { get; set; }
        public DateTime cdet_FechaCrea { get; set; }
        public int? cdet_UserMofica { get; set; }
        public DateTime? cdet_FechaModifica { get; set; }

        public virtual tbUsuario cdet_UserCreaNavigation { get; set; }
        public virtual tbUsuario cdet_UserMoficaNavigation { get; set; }
        public virtual tbCombo cdet_comb { get; set; }
        public virtual tbInsumo cdet_insu { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalles { get; set; }
    }
}