// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbHorario
    {
        public tbHorario()
        {
            tbProyecciones = new HashSet<tbProyeccione>();
        }

        public int hor_Id { get; set; }
        public TimeSpan hor_HoraInicio { get; set; }
        public TimeSpan hor_HoraFin { get; set; }

        public virtual ICollection<tbProyeccione> tbProyecciones { get; set; }
    }
}