// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbMunicipio
    {
        public tbMunicipio()
        {
            tbSucursales = new HashSet<tbSucursale>();
        }

        public int muni_Id { get; set; }
        public int muni_depId { get; set; }
        public string muni_Descripcion { get; set; }
        public bool? muni_Estado { get; set; }
        public int muni_UserCrea { get; set; }
        public DateTime? muni_FechaCrea { get; set; }
        public int? muni_UserMofica { get; set; }
        public DateTime? muni_FechaModifica { get; set; }

        public virtual tbUsuario muni_UserCreaNavigation { get; set; }
        public virtual tbUsuario muni_UserMoficaNavigation { get; set; }
        public virtual tbDepartamento muni_dep { get; set; }
        public virtual ICollection<tbSucursale> tbSucursales { get; set; }
    }
}