// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbRolesPantalla
    {
        public int ropa_Id { get; set; }
        public int ropa_Rol { get; set; }
        public int ropa_Pantalla { get; set; }
        public bool? ropa_Estado { get; set; }
        public int ropa_UserCrea { get; set; }
        public DateTime? ropa_FechaCrea { get; set; }
        public int? ropa_UserMofica { get; set; }
        public DateTime? ropa_FechaModifica { get; set; }

        public virtual tbPantalla ropa_PantallaNavigation { get; set; }
        public virtual tbRole ropa_RolNavigation { get; set; }
        public virtual tbUsuario ropa_UserCreaNavigation { get; set; }
        public virtual tbUsuario ropa_UserMoficaNavigation { get; set; }
    }
}