// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbtempFacturaDetalle
    {
        public int? fade_Factura { get; set; }
        public int? fade_Proyeccion { get; set; }
        public int? fade_Tickets { get; set; }
        public string fade_ContenidoCombo { get; set; }
        public string fade_ContenidoInsumo { get; set; }
        public int? fade_Pago { get; set; }
        public int? fade_Total { get; set; }
        public int? fade_UsuCrea { get; set; }
    }
}