// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class tbTicket
    {
        public int tick_Id { get; set; }
        public int? tick_Factura { get; set; }
        public int? tick_Proyeccion { get; set; }
        public int? tick_Asiento { get; set; }
        public bool? tick_Estado { get; set; }
        public int tick_UsuCrea { get; set; }
        public DateTime? tick_FechaCrea { get; set; }
        public int? tick_UsuMofica { get; set; }
        public DateTime? tick_FechaModifica { get; set; }

        public virtual tbAsiento tick_AsientoNavigation { get; set; }
        public virtual tbFactura tick_FacturaNavigation { get; set; }
        public virtual tbProyeccione tick_ProyeccionNavigation { get; set; }
    }
}