// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class trabajo
    {
        public int id { get; set; }
        public string trabajo1 { get; set; }
    }
}