// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_Categoria
    {
        public int cate_Id { get; set; }
        public string cate_Nombre { get; set; }
        public bool? cate_Estado { get; set; }
        public int? cate_UsuarioCreador { get; set; }
        public DateTime? cate_FechaCreacion { get; set; }
        public int? cate_UsuarioModificador { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }
    }
}