// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_Departamento
    {
        public int dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public bool dept_Estado { get; set; }
        public int dept_UserCrea { get; set; }
        public DateTime? dept_FechaCrea { get; set; }
        public int? dept_UserMofica { get; set; }
    }
}