// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_MetodoPago
    {
        public int pago_Id { get; set; }
        public string pago_Descripcion { get; set; }
        public int? pago_Estado { get; set; }
        public int? pago_UsuarioCreador { get; set; }
        public DateTime? pago_FechaCreacion { get; set; }
        public int? pago_UsuarioModificador { get; set; }
        public DateTime? pago_FechaModificacion { get; set; }
    }
}