// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_Proyeccione
    {
        public int proy_Id { get; set; }
        public int? proy_Pelicula { get; set; }
        public string peli_Titulo { get; set; }
        public int? proy_Sala { get; set; }
        public int sala_Butacas { get; set; }
        public int sala_Tipo { get; set; }
        public string casa_Categoria { get; set; }
        public int? casa_Precio { get; set; }
        public int? proy_Horario { get; set; }
        public string hor_HoraInicio { get; set; }
        public string hor_HoraFin { get; set; }
        public bool? proy_Estado { get; set; }
    }
}