// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbHorario
    {
        public int hor_Id { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
    }
}