// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbInsumo
    {
        public int insu_Id { get; set; }
        public string insu_Descripcion { get; set; }
        public decimal insu_Precio { get; set; }
        public string insu_href { get; set; }
        public string insu_src { get; set; }
        public string insu_alt { get; set; }
        public bool insu_Estado { get; set; }
        public int insu_UserCrea { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public DateTime insu_FechaCrea { get; set; }
        public int? insu_UsuarioModifica { get; set; }
        public DateTime? insu_FechaModifica { get; set; }
    }
}