// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbSUCURSAL
    {
        public int sucu_Id { get; set; }
        public string sucu_Nombre { get; set; }
        public string sucu_Direccion { get; set; }
        public int sucu_Ciudad { get; set; }
        public bool sucu_Estado { get; set; }
        public int sucu_UserCrea { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public DateTime sucu_FechaCrea { get; set; }
        public int? sucu_UsuarioModifica { get; set; }
        public DateTime? sucu_FechaModifica { get; set; }
    }
}