// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbDirector
    {
        public int dire_Id { get; set; }
        public string dire_Nombres { get; set; }
        public string dire_Apellidos { get; set; }
        public DateTime? dire_FechaNacimiento { get; set; }
        public string dire_Sexo { get; set; }
        public bool? dire_Estado { get; set; }
        public int dire_UsuCrea { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public DateTime? dire_FechaCrea { get; set; }
        public int? dire_UsuMofica { get; set; }
        public DateTime? dire_FechaModifica { get; set; }
    }
}