// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbFactura
    {
        public int fact_Id { get; set; }
        public int? fact_Cliente { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_RTN { get; set; }
        public bool? fact_Estado { get; set; }
        public int fact_UsuCrea { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public DateTime? fact_FechaCrea { get; set; }
        public int? fact_UsuMofica { get; set; }
        public DateTime? fact_FechaModifica { get; set; }
    }
}