// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbFacturaDetalle1
    {
        public int fade_Id { get; set; }
        public int? fade_Factura { get; set; }
        public string clie_RTN { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public int? fade_Proyeccion { get; set; }
        public string peli_Titulo { get; set; }
        public int sala_Id { get; set; }
        public string casa_Categoria { get; set; }
        public int? fade_Tickets { get; set; }
        public decimal? casa_Precio { get; set; }
        public string fade_Combo_Id { get; set; }
        public string fade_Combo_Cantidad { get; set; }
        public string comb_Descripcion { get; set; }
        public string fade_ComboDetalle { get; set; }
        public string fade_ComboDetalle_Cantidad { get; set; }
        public int? fade_Pago { get; set; }
        public string pago_Descripcion { get; set; }
        public int? fade_Total_Tickets { get; set; }
        public decimal? fade_Total_Combo { get; set; }
        public decimal? fade_Total { get; set; }
        public bool? fade_Estado { get; set; }
        public int fade_UsuCrea { get; set; }
        public DateTime? fade_FechaCrea { get; set; }
        public int? fade_UsuMofica { get; set; }
        public DateTime? fade_FechaModifica { get; set; }
    }
}