// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbEmpleado
    {
        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellidos { get; set; }
        public string empl_Sexo { get; set; }
        public int empl_Estadocivil { get; set; }
        public string estc_Descripcion { get; set; }
        public int muni_depId { get; set; }
        public string dept_Descripcion { get; set; }
        public int empl_Muni { get; set; }
        public string muni_Descripcion { get; set; }
        public int empl_Cargo { get; set; }
        public string carg_Cargo { get; set; }
        public int? empl_Sucursal { get; set; }
        public string sucu_Nombre { get; set; }
        public string empl_DireccionExacta { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Telefono { get; set; }
        public int empl_UsuarioCreador { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public int? empl_UsuarioModificado { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }
    }
}