// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbComboDetalle
    {
        public int cdet_Id { get; set; }
        public int cdet_combId { get; set; }
        public string comb_Descripcion { get; set; }
        public decimal comb_Precio { get; set; }
        public int cdet_insuId { get; set; }
        public string insu_Descripcion { get; set; }
        public decimal insu_Precio { get; set; }
        public bool cdet_Estado { get; set; }
        public int cdet_UserCrea { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public DateTime cdet_FechaCrea { get; set; }
        public int? cdet_UserMofica { get; set; }
        public DateTime? cdet_FechaModifica { get; set; }
    }
}