// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_tbFacturaDetalle
    {
        public int? fade_Factura { get; set; }
        public string clie_RTN { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string peli_Titulo { get; set; }
        public int? fade_Tickets { get; set; }
    }
}