// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Cine.Entities.Entities
{
    public partial class VW_Usuario
    {
        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Contrasenia { get; set; }
        public int user_Empleado { get; set; }
        public string Nombre { get; set; }
        public int user_Rol { get; set; }
        public string role_Nombre { get; set; }
        public bool user_EsAdmin { get; set; }
        public bool user_Estado { get; set; }
        public int user_UsuarioCrea { get; set; }
        public DateTime user_FechaCrea { get; set; }
        public int? user_UsuarioModifica { get; set; }
        public DateTime? user_FechaModifica { get; set; }

        [NotMapped]

        public int empl_Sucursal { get; set; }

        [NotMapped]
        public string carg_Cargo { get; set; }

        [NotMapped]
        public string sucu_Nombre { get; set; }

        [NotMapped]
        public string EsAdmin { get; set; }

    }
}